apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dummy
  template:
    metadata:
      labels:
        name: dummy
    spec:
      serviceAccountName: dummy
      containers:
        - name: dummy
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - dummy
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "dummy"
